import React from 'react'
import PropTypes from 'prop-types'
import Head from 'next/head'
import Navbars from './Navbars'
import styles from '../styles/Home.module.css' 
import Image from 'next/image'

function AppLayout({ children, title, description }) {
    return (
        <div>
            <Head>
                <title> Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbars className="navbars"></Navbars>
            <main>
                {children}
            </main>
            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    )
}

AppLayout.defaultProps = {
    title: "App",
    description: "Buenos"

};

export default AppLayout
